### ISSUE TITLE
ACEMQ deployment on IKS cluster with helm charts

### ISSUE THREAD

**Issue by rudra108** [ot4i/ace-docker#103]
Hi,
We are trying to install acemq image on a iks cluster with help of following helm charts 

https://github.com/IBM/charts/tree/master/stable/ibm-ace-server-dev

But this charts only installs ACE without MQ.
The values.yaml, however, does list acemq image to be installed. 

_image:
  aceonly: ibmcom/ace:11.0.0.6
  acemqclient: ibmcom/ace-mqclient:11.0.0.6
  **acemq: ibmcom/ace-mq:11.0.0.6**
  configurator: ibmcom/ace-icp-configurator:11.0.0.6
  designerflows: ibmcom/ace-designer-flows:11.0.0.6_
  
  
But the template/deployment.yaml doesn't have support for that. Or may be I am missing something.
Do we have a helm chart that istalles both MQ and ACE?
Alternatively, please suggest any tweaks that can be done in this helm chart to support both ACE and MQ deployments on my iks cluster.

Note: this iks cluster is running on ibmcloud.

**Comment by IBMRob** [comment]
Hi - The chart you have referenced supports creating an ACE with MQ image, you need to change the value for `imageType` to `acemqserver`. When using MQ we do not use deployments, we use stateful sets because MQ is stateful. 

The charts are only tested when running on Openshift with IBM Common Services. They are not designed to run standalone or on IKS. 

I would highly recommend not running with MQ in the same image if you can and creating a separate MQ container using the MQ Container charts and images. This means you can manage each separately such that you are not restricted on how you scale ACE. As of ACE 11.0.0.7 all EDA also work using a default client connection to a remote queue manager removing the requirement to need a local QM. 

Note that in the future we are going to stop shipping an ACE+MQ image.
