### ISSUE TITLE
how to apply fix pack on ACE 11.0.0.5 

### ISSUE THREAD

**Issue by har2103** [ot4i/ace-docker#74]
Hi Rob,

I have created a new image with IBM ACE 11.0.0.5 using tar (11.0.0-ACE-LINUXX64-FP0005.tar) but with this image timer notifications is not supported. and IBM has provided fix pack (11.0.0.5-ACE-LinuxX64-TFIT29693.tar ) . so I want to know how should apply this fix pack in openshift conatiner? this will require a new image creation and what steps we should follow.

Looking forward for your response as we have to apply asap.

**Comment by mattbaileyuk** [comment]
@har2103 It looks like you're trying to apply an APAR rather than a new Fix Pack (i.e. FP5 on an FP4 image), and for that I think the best way would be to untar the original ACE 11.0.0.5 package, apply the APAR follow the instructions in that tar file (`11.0.0.5-ACE-LinuxX64-TFIT29693.tar`) to your extracted 11.0.0.5. Then package those directories back up as a tar and use it to build your Docker image.

**Comment by IBMRob** [comment]
Please see the updates provided by https://github.com/ot4i/ace-docker/pull/76

**Comment by har2103** [comment]
thanks mattbaileyuk  and IBMRob .
