### ISSUE TITLE
unable to configure postfix in acemq container

### ISSUE THREAD

**Issue by har2103** [ot4i/ace-docker#89]
Hi Team,

We have build an acemq container using script  available on github (ot4i/ace-docker). we have a requirement to install postfix to send mail from container. i have added yum install postfix in docker file to install. its getting installed but unable to configure mail. it gives below error

[root@acemqa-pod-4-txcqc postfix]# sudo systemctl restart postfix
Failed to get D-Bus connection: Operation not permitted

though root is a super user it still doesnt allow  to perform such operation.

Need your suggestion how can i overcome this issue.

**Comment by IBMRob** [comment]
Hi,

Unfortunately this isn't something we have attempted before. I'm pretty sure its failing because that command is designed for a real linux system and not within docker which doesn't run all the same services. We don't run systemd within our ACE container. If you need to run another background micro service within the container you will need to customise the image to support this. Currently its designed to run a single process.
